FROM apache/airflow:2.7.1

RUN pip install --upgrade pip setuptools wheel

# Copy the requirements.txt file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
