FROM python:3.9-slim

WORKDIR /mlflow

RUN pip install mlflow

ENV BACKEND_URI=sqlite:///mlflow.db

EXPOSE 5000

CMD ["mlflow", "ui", "--backend-store-uri", "sqlite:///mlflow.db", "--host", "0.0.0.0"]